[firefox]
src.manual = "132.0.1"
fetch.url = "https://archive.mozilla.org/pub/firefox/releases/$ver/source/firefox-$ver.source.tar.xz"
[zen-browser]
fetch.github = "zen-browser/desktop"
src.manual = "1.0.1-a.19"
git.fetchSubmodules = true

